---

- name: Configure syslog to send logs over UDP to 10.0.10.10
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Configure rsyslog to send logs over UDP
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^\\*\\.\\*\\s+@'
        line: '*.* @10.0.10.10:514'
        backup: yes
      notify:
        - restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
