---
- name: Clean Ubuntu system
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean APT cache
      apt:
        autoclean: yes

    - name: Clean thumbnail cache
      file:
        path: ~/.cache/thumbnails
        state: absent
      become_user: "{{ ansible_user }}"
      when: ansible_user_dir is defined

    - name: Clear systemd journal logs
      systemd:
        name: systemd-journald
        state: restarted

    - name: Reboot the server if necessary
      reboot:
        test_command: uptime
        reboot_timeout: 300


#This playbook will perform the following tasks:

#1. Update the APT cache to ensure the package information is up-to-date.
#2. Remove unnecessary packages using apt autoremove.
#3. Clean the APT cache using apt autoclean.
#4. Remove the thumbnail cache for the current user (if applicable).
#5. Clear systemd journal logs to free up disk space.