---
- name: Clean Ubuntu system
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean APT cache
      apt:
        autoclean: yes

    - name: Clean thumbnail cache
      file:
        path: ~/.cache/thumbnails
        state: absent
      become_user: "{{ ansible_user }}"
      when: ansible_user_dir is defined

    - name: Clear systemd journal logs
      systemd:
        name: systemd-journald
        state: restarted
