---

#Ansible playbook that performs various system cleaning tasks on Ubuntu Linux, including removing unnecessary packages, cleaning the APT cache, removing old kernels, cleaning thumbnail cache, and clearing systemd journal logs:

- name: Clean Ubuntu system
  hosts: your_target_host
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean APT cache
      apt:
        autoclean: yes

    - name: Remove old kernels
      shell: dpkg -l | awk '/linux-image-*/ {print $2}' | grep -v $(uname -r) | xargs sudo apt-get -y purge

    - name: Clean thumbnail cache
      file:
        path: ~/.cache/thumbnails
        state: absent
      become_user: "{{ ansible_user }}"
      when: ansible_user_dir is defined

    - name: Clear systemd journal logs
      systemd:
        name: systemd-journald
        state: restarted

#This playbook will perform the following tasks:

#1. Update the APT cache to ensure the package information is up-to-date.
#2. Remove unnecessary packages using apt autoremove.
#3. Clean the APT cache using apt autoclean.
#4. Remove old kernels to free up disk space (This is optional, and you should consider the implications of removing old kernels).
#5. Remove the thumbnail cache for the current user (if applicable).
#6. Clear systemd journal logs to free up disk space.