---

- name: Update Linux packages using apt
  hosts: all
  become: yes
  become_user: javierchan
  tasks:

    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock-frontend"

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to their latest version
      apt:
        name: '*'
        state: latest
        force_apt_get: yes

    - name: Reboot the server if necessary
      reboot:
        test_command: uptime
        reboot_timeout: 300